exports.missingMailOrPassword = "Missing email or password"
exports.passwordTooWeak = "Password is too weak..."
exports.passwordsNotMatching = "Passwords are not matching"
exports.tasksNotFound = "Unable to load tasks list"
exports.taskFieldIsEmpty = "Error task name field is empty"
exports.addingTaskFailled = "adding new task failled "

exports.frNoUserFound = "Cet e-mail ne correspond à aucun utilisateur"
exports.frMailAlreadyUsed = "Le mail saisi correspond à un compte utilisateur"
exports.frPasswordTooWeak = "Le mot de passe est trop faible (minimum 8 caractères dont 1 majuscule, 1 minuscule, un caractère spécial et un nombre)"   
exports.frBadPassword = "Le mot de passe n'est pas le bon"
exports.frPasswordsNotMatching = "Les mots de passe ne correspondent pas"
exports.frEmptyField = "L'un des champs est vide"
exports.frOups = "Oups .. un problème est survenu !"